import { describe, expect, it } from "vitest";
import { type BlockNode, parseInline, parseMarkdown } from "./markdown";

/** The shape `cliff.toml` actually produces, generated by git-cliff 2.14.1. */
const RELEASE_BODY = `## What's Changed

### Features
- **player:** Add playlist panel
- Drop the legacy webm fallback

### Bug Fixes
- **window:** Keep the aspect ratio for ultrawide video

### Performance
- Avoid a full re-render on seek
`;

describe("release notes", () => {
  it("reads headings, groups and their items", () => {
    expect(parseMarkdown(RELEASE_BODY)).toEqual([
      { type: "heading", level: 2, content: [{ type: "text", value: "What's Changed" }] },
      { type: "heading", level: 3, content: [{ type: "text", value: "Features" }] },
      {
        type: "list",
        ordered: false,
        items: [
          [
            { type: "strong", value: "player:" },
            { type: "text", value: " Add playlist panel" },
          ],
          [{ type: "text", value: "Drop the legacy webm fallback" }],
        ],
      },
      { type: "heading", level: 3, content: [{ type: "text", value: "Bug Fixes" }] },
      {
        type: "list",
        ordered: false,
        items: [
          [
            { type: "strong", value: "window:" },
            { type: "text", value: " Keep the aspect ratio for ultrawide video" },
          ],
        ],
      },
      { type: "heading", level: 3, content: [{ type: "text", value: "Performance" }] },
      {
        type: "list",
        ordered: false,
        items: [[{ type: "text", value: "Avoid a full re-render on seek" }]],
      },
    ]);
  });

  it("keeps a heading that follows a list without a blank line", () => {
    const blocks = parseMarkdown("### A\n- one\n### B\n- two");
    expect(blocks.map((block) => block.type)).toEqual(["heading", "list", "heading", "list"]);
  });

  it("opens a new list when the marker type changes", () => {
    const blocks = parseMarkdown("- one\n1. first\n- two");
    expect(blocks).toEqual([
      { type: "list", ordered: false, items: [[{ type: "text", value: "one" }]] },
      { type: "list", ordered: true, items: [[{ type: "text", value: "first" }]] },
      { type: "list", ordered: false, items: [[{ type: "text", value: "two" }]] },
    ]);
  });

  it("reads a horizontal rule as a rule rather than a list", () => {
    expect(parseMarkdown("---\n***\n___")).toEqual<BlockNode[]>([
      { type: "rule" },
      { type: "rule" },
      { type: "rule" },
    ]);
  });

  it("joins wrapped lines into one paragraph and splits on blank lines", () => {
    expect(parseMarkdown("one\ntwo\r\n\r\nthree\r\n")).toEqual([
      { type: "paragraph", content: [{ type: "text", value: "one two" }] },
      { type: "paragraph", content: [{ type: "text", value: "three" }] },
    ]);
  });

  it("returns nothing for an empty body", () => {
    expect(parseMarkdown("")).toEqual([]);
    expect(parseMarkdown("\n \n\t\n")).toEqual([]);
  });

  it("never produces markup from remote text", () => {
    const blocks = parseMarkdown("- <script>alert(1)</script>\n- <img src=x onerror=alert(1)>");
    expect(blocks).toEqual([
      {
        type: "list",
        ordered: false,
        items: [
          [{ type: "text", value: "<script>alert(1)</script>" }],
          [{ type: "text", value: "<img src=x onerror=alert(1)>" }],
        ],
      },
    ]);
  });

  it("does not treat a hashtag or an email address as a heading or a link", () => {
    expect(parseMarkdown("#1 is not a heading")).toEqual([
      { type: "paragraph", content: [{ type: "text", value: "#1 is not a heading" }] },
    ]);
    expect(parseMarkdown("write to a@b.com")).toEqual([
      { type: "paragraph", content: [{ type: "text", value: "write to a@b.com" }] },
    ]);
  });
});

describe("inline runs", () => {
  it("reads bold, code and links", () => {
    expect(parseInline("**bold** and `code` and [mirror](https://example.com/x)")).toEqual([
      { type: "strong", value: "bold" },
      { type: "text", value: " and " },
      { type: "code", value: "code" },
      { type: "text", value: " and " },
      { type: "link", value: "mirror", href: "https://example.com/x" },
    ]);
  });

  it("leaves an unpaired delimiter as text", () => {
    expect(parseInline("**not closed")).toEqual([{ type: "text", value: "**not closed" }]);
    expect(parseInline("a * b")).toEqual([{ type: "text", value: "a * b" }]);
  });
});
